### PR TITLE
Pop up button disabled fix

### LINKED ISSUE #40: [Login popup] Login button is clickable without entering any data in Email and Password field
**Environment:** Windows10 21H2, Chrome 112.0.5615.138
**Reproducible:** always

**Preconditions**
The user is on website

**Steps to reproduce**

1. Click Login button in the upper right corner of the header
2. Hover the mouse that the cursor fall on Login button and hover back outside
3. Click on Login button

**Expected result**
The Login button should be unclickable, nothing should happen

### PR DESCRIPTION
**Pull request by markgol777**

### CODE REVIEW

**Review by Yaroslav-Yakovlev — APPROVED** [review]

**Review by Bakalina — APPROVED** [review]

**Review by Yaroslav-Yakovlev — APPROVED** [review]

**Review by mistercapxx — APPROVED** [review]

**Review by miller-113 — APPROVED** [review]

**Review by CallMeMaverick — APPROVED** [review]

File: src/containers/guest-home-page/login-form/LoginForm.jsx [hunk 1]
```diff
@@ -19,14 +19,34 @@ const LoginForm = ({
...
+  const { authLoading } = useSelector((state) => state.appMain)
+  const { openModal } = useModalContext()
+  const { t } = useTranslation()
+
   const { inputVisibility: passwordVisibility, showInputText: showPassword } =
     useInputVisibility(errors.password)
 
-  const { authLoading } = useSelector((state) => state.appMain)
+  const emailRef = useRef(null)
+  const passwordRef = useRef(null)
```
Comment (nrevutska) [inline src/containers/guest-home-page/login-form/LoginForm.jsx]: Why do we need these refs?

**Review by nrevutska — CHANGES_REQUESTED** [review]
let's try to pass the quality gate
image

File: src/containers/guest-home-page/login-form/LoginForm.jsx (hunk 1 above)
Comment (markgol777) [reply src/containers/guest-home-page/login-form/LoginForm.jsx]: removed

**Review by nrevutska — APPROVED** [review]
